### ISSUE TITLE
Slides stopped working?

### ISSUE THREAD

**Issue by simongis** [Datapolitan-Training/qgis-training#7]
Loving this material.  I am having an issue with the slides:

If I open up [the slides](http://www.datapolitan.com/DOT_GIS/20160610_Intermediate_GIS/#1), they do not render as expected.  I get the underlying HTML + MarkDown

**Comment by richarddunks** [comment]
Thanks @simongis for this and my sincere apologies for taking so long to getting around to this. The content is now reformatted and has a new home [here](https://github.com/Datapolitan-Training/intermediate-gis). You can access the slides [here](http://bit.ly/intermediate-gis). Thank you again for contributing to making this content better and please let me know what you think of the new slides!
